name: Send Message to WeCom

on:
  # 定时触发，每天 UTC 时间 4 点（北京时间 12 点）运行
  schedule:
    - cron: '0 4 * * *'
  # 也可以手动触发
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Send message to WeCom
        env:
          WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
          JSON_CONTENT: ${{ secrets.WECOM_CONTENT }}  # 重命名为 JSON_CONTENT 更清晰
        run: |
          python - <<EOF
          import requests
          import json
          
          url = "$WEBHOOK_URL"
          # 直接解析环境变量中的 JSON 字符串
          data = json.loads(r'''$JSON_CONTENT''')
          
          response = requests.post(url, json=data)
          print("Response status code:", response.status_code)
          print("Response text:", response.text)
          
          if response.status_code == 200:
              result = response.json()
              if result.get('errcode') == 0:
                  print("Message sent successfully")
              else:
                  print(f"Failed to send message: {result.get('errmsg')}")
          else:
              print(f"Request failed with status code {response.status_code}")
          EOF
